spring:
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        trace: false
  datasource:
    url: jdbc:h2:file:./db/filmorate
    driver-class-name: org.h2.Driver
    username: sa
    password: password


